apiVersion: v1
kind: Service
metadata:
  name: svc3
  namespace: argo-deploy
spec:
  selector:
     app: nginxapp
  type: NodePort
  ports:
    - name: port1
      port: 80
      targetPort: 80
      nodePort: 30888